### ISSUE TITLE
update job eventTriggerConfig using cli and --yaml flag

### ISSUE THREAD

**Issue by jason-berk-k1x** [microsoft/azure-container-apps#1014]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest#az-containerapp-job-update shows an option for `[--yaml]`, but the example is for a container app, not a job.  I need to know how to configure the `Trigger Configuration` in my yaml file.

### Steps to reproduce
1. setup a manual job following [this tutorial](https://learn.microsoft.com/en-us/azure/container-apps/jobs?tabs=azure-cli#manual-jobs)
2. try and update the job to be an Event triggered job with the CLI: `az containerapp job update --name job-name --resource-group rg-job-group --yaml config.yml` (where the config updates any of the job configuration, but specifically sets `triggerType` to `Event`

**Expected behavior** [What you expected to happen.]

trigger type updates accordingly

**Actual behavior** [What actually happened.]

fails with

>(ContainerAppsJobTriggerConfigurationMissing) Container apps job 'xxxxx' must have Trigger Configuration corresponding to trigger type 'Event'

setting my eventTriggerConfig to 

```
eventTriggerConfig:
      minExecutions: 0
      maxExecutions: 10
      scale:
        rules:
        - name: queue-based
          type: azure-servicebus
          auth:
            connection: service-bus-conn
          metadata:
            queueName: my-queue-name
            messageCount: 1
    replicaRetryLimit: 0
    replicaTimeout: 60
```

fails with

>Invalid YAML provided. Please see https://aka.ms/azure-container-apps-yaml for a valid YAML spec.

**Screenshots**         

### Additional context

my goal is to have Terraform setup a generic manual job and all the ancillary bits.  Then, individuals repos can create a pipeline to update the job using the AZ CLI to be event driven, add in secrets / env / acr registry / etc.  All the other settings work, but I can't for the life of me figure out what the `eventTriggerConfig` format is

**Comment by vinisoto** [comment]
Thanks for reaching out @jason-berk-k1x. 

We will fix our docs/CLI help so that the YAML reference in points to a Jobs spec and not a Container App

**Comment by vinisoto** [comment]
We have added a YAML example for Jobs here: https://learn.microsoft.com/en-us/azure/container-apps/azure-resource-manager-api-spec?tabs=yaml#job-examples

We will change the link provided in the CLI error message to point to the new YAML example

**Comment by jason-berk-k1x** [comment]
thanks....  it would be really nice to also reference the trigger config options as well....  I found them here

https://learn.microsoft.com/en-us/azure/templates/microsoft.app/2023-05-01/jobs?pivots=deployment-language-arm-template#resource-format-1

**Comment by vinisoto** [comment]
Fixed with: https://github.com/Azure/azure-cli/pull/28799

**Comment by VictorioBerra** [comment]
Those docs at https://aka.ms/azure-container-apps-job-yaml still don't mention `eventTriggerConfig`
