### ISSUE TITLE
az containerapp hostname bind failed to identify  the container app environment 

### ISSUE THREAD

**Issue by ttaher** [microsoft/azure-container-apps#1099]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

The behavior of this command has been altered by the following extension: containerapp
(ParentResourceNotFound) Failed to perform 'read' on resource(s) of type 'managedEnvironments/managedCertificates', because the parent resource '/subscriptions/xxxx/resourceGroups/sam-taxonomyui-dev-rg/providers/Microsoft.App/managedEnvironments/sam-containerappsenvironment-dev' could not be found.

### Steps to reproduce

**Expected behavior** [What you expected to happen.]

**Actual behavior** [What actually happened.]

**Screenshots**         

### Additional context
it will be good to not depend on the resource group to get the environment because container environment could be in different resource group , then refer to the environment with environment Id as a resource id

**Comment by Greedygre** [comment]
Hi @ttaher 

Thanks for opening this issue.
This issue has been fixed in azure-cli version `2.57.0` in PR:

[[Containerapp] `az containerapp hostname bind`: Fix an issue about parsing the environment's resource group when the `--environment` is a resource id by Greedygre · Pull Request #28063 · Azure/azure-cli (github.com)](https://github.com/Azure/azure-cli/pull/28063)

Can you upgrade the azure-cli with command `az upgrade` and try again? Thanks!

**Comment by ttaher** [comment]
@Greedygre  we still have the same error, it can't ready the **managedEnvironments/managedCertificates** created in the azure container environment to bind it with container custom domain 
![image](https://github.com/microsoft/azure-container-apps/assets/19903942/568e8211-329b-4da3-9e23-6d9c613928d5)
to be used here 
![image](https://github.com/microsoft/azure-container-apps/assets/19903942/097061d2-1dec-40a9-bec3-583d50b633dd)

**Comment by Greedygre** [comment]
Hi @ttaher 

Do you still have error on Azure-cli after upgrade version `>= 2.57.0`?
If so, please paste the error and also show the result of command `az version`.

**Comment by ttaher** [comment]
@Greedygre yes, still have it 
i am using azure portal bash cmd and version is here 
{
  "azure-cli": "2.57.0",
  "azure-cli-core": "2.57.0",
  "azure-cli-telemetry": "1.1.0",
  "extensions": {
    "ai-examples": "0.2.5",
    "application-insights": "0.1.19",
    "containerapp": "0.3.27",
    "ml": "2.22.0",
    "ssh": "2.0.2"
  }
}

**Comment by Greedygre** [comment]
> @Greedygre yes, still have it i am using azure portal bash cmd and version is here { "azure-cli": "2.57.0", "azure-cli-core": "2.57.0", "azure-cli-telemetry": "1.1.0", "extensions": { "ai-examples": "0.2.5", "application-insights": "0.1.19", "containerapp": "0.3.27", "ml": "2.22.0", "ssh": "2.0.2" } }

Thanks for your reply.
The version of extension `containerapp` also needs to be update to `>=0.3.43`, please try this command to update it:
`az extension add -n containerapp --upgrade`

**Comment by ttaher** [comment]
this is the full command an result 

![image](https://github.com/microsoft/azure-container-apps/assets/19903942/6ddb2e04-6eb6-4921-87ed-0f08975ee7b4)

**Comment by Greedygre** [comment]
> @Greedygre this is the full command an result
> 
> ![image](https://private-user-images.githubusercontent.com/19903942/308608562-6ddb2e04-6eb6-4921-87ed-0f08975ee7b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzQ0NTYsIm5iZiI6MTcwOTEzNDE1NiwicGF0aCI6Ii8xOTkwMzk0Mi8zMDg2MDg1NjItNmRkYjJlMDQtNmViNi00OTIxLTg3ZWQtMGYwODk3NWVlN2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE1MjkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MDFmMTVlY2YzY2QwZGZjOGExZTExN2ExNmNiOTUxNjUwOTc4YzUwZDY5NzgwYTAwYWI2MmMxNTZlZjU3OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-0Um3g0iT4djHHAhApu5xScLIzcBCd8rQa0_eq9aD2s)

Thanks.
Can you try to input the environment resource id for `--environment`?
If the containerapp and the environment are no in the same resource group, need to input the resource id of the environment:
` --environment -e       : Name or resource id of the Container App environment.`

**Comment by ttaher** [comment]
@Greedygre  Thanks a lot it is fixed now really great support
