### ISSUE TITLE
Image Pull Failures

### ISSUE THREAD

**Issue by jason-berk-k1x** [microsoft/azure-container-apps#1210]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
I have created via terraform a Container App Environment and Job.  The job is given a managed identity which is then granted AcrPull rights and Key Vault rights.   the same terraform is ran for two different jobs, each getting its own env and vault.  All pull from the same ACR

one of my jobs works and can pull images from ACR.  The other fails with authorization errors (after it said the pull was successful)

**Expected behavior** [What you expected to happen.]

job and pull images from ACR

**Actual behavior** [What actually happened.]

image pull fails

**Screenshots**         

the job's managed identity is granted ACR pull right in my ACR:

![Screenshot 2024-06-24 at 5 21 10 PM](https://github.com/microsoft/azure-container-apps/assets/148882427/871fea80-3903-4660-8e29-a184fc326361)

the identity assigned to the job shows it can pull from the ACR in the "global" sub:

![Screenshot 2024-06-24 at 5 19 42 PM](https://github.com/microsoft/azure-container-apps/assets/148882427/05c60eb0-f1c0-4a0f-8c48-e3460aaf46aa)

when I trigger a job run by putting a message in a queue, the pull fails:

![Screenshot 2024-06-24 at 5 18 29 PM](https://github.com/microsoft/azure-container-apps/assets/148882427/7928599e-2b80-4e68-ae45-c682aadf0a93)

### Additional context
my jobs are running in the "dev" sub, but the ACR lives in the "global" sub

**Comment by jason-berk-k1x** [comment]
seems related to: https://github.com/microsoft/azure-container-apps/issues/1211

**Comment by vturecek** [comment]
@jason-berk-k1x are you still seeing this issue?

**Comment by MDendura** [comment]
I seem to be having exactly the same problem. Deployments using Terraform in a pipeline to an existing Container Apps Environment work fine, but fail when deploying to a new CAE.

Each CAE has its own Managed Identity with `AcrPull` permissions on the same Container Registry. The Container Registry is in a separate subscription.

**Comment by jason-berk-k1x** [comment]
> Deployments using Terraform in a pipeline to an existing Container Apps Environment work fine, but fail when deploying to a new CAE.

personally, I do use TF to do deployments....wrong tool for the job IMO.  TF is for infra, not build / deploy lifecycle.  I use TF to  create the CAE and a job/app that is just the quickstart container that I pushed into my ACR.  this proves all the identity setup is correct to pull images from ACR and read secrets from my vault.  my deploy is a github action that uses the az cli and a yaml config file

> Each CAE has its own Managed Identity with AcrPull permissions on the same Container Registry.

Maybe this is just a typo, but the CAE doesn't get an identity.... the apps/jobs do

**Comment by MDendura** [comment]
> personally, I do use TF to do deployments....wrong tool for the job IMO. TF is for infra, not build / deploy lifecycle. I use TF to create the CAE and a job/app that is just the quickstart container that I pushed into my ACR

I quite agree, though clearly I didn't do a very good job of explaining my setup :)

I use my Terraform pipeline to create the apps based on the `latest` image, just as part of the infrastructure setup. For deploying new versions of my container images I use a couple of different DevOps pipelines that use the AzCli, creating a new Container App revision that references a version number tagged container image.

> Maybe this is just a typo, but the CAE doesn't get an identity.... the apps/jobs do

You're 100% right - again, I didn't explain this very well. The apps different apps use different Managed Identities, though these have the same permissions applied.

---

Interestingly I have been doing some more testing today and now get the same image pull error from my non-Terraform pipelines i.e. those that use the AzCli that have been working reliably until now:

```json
        "statusMessage": "{\"status\":\"Failed\",\"error\":{\"code\":\"ResourceOperationFailure\",\"message\":\"The resource operation completed with terminal provisioning state 'Failed'.\",\"details\":[{\"code\":\"ContainerAppOperationError\",\"message\":\"Failed to provision revision for container app 'my-container-app'. Error details: The following field(s) are either invalid or missing. Field 'template.containers.containerappname.image' is invalid with details: 'Invalid value: \\\"myacrurl.azurecr.io/repo/image-name:1.0.169\\\": unable to pull image using Managed identity /subscriptions/mySubId/resourceGroups/my-resource-group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/my-umid for registry myacrurl.azurecr.io';..\"}]}}",
```

I've replaced the resource names in the message, but it seems to be the same image pull error so perhaps is related to what OP has been seeing.

@jason-berk-k1x do you see the same in the Activity Log for your Container App?

**Comment by MDendura** [comment]
I'm still facing this issue, now across both of my Container App Environments and whether I deploy via Terraform or the AzCli. I haven't heard back from my email to acasupport yet either.

It's become quite a problem and is really giving me regrets about going with Container Apps over AKS. These kinds of random failures make me wonder whether Container Apps can be considered production-ready at all.

**Comment by jason-berk-k1x** [comment]
I've actually been looking into other options outside of ACA.  Been burnt one too many times by this service.  Until it becomes more stable and the docs get better, I'm looking at other solutions

**Comment by robindegreve** [comment]
Same issue here. I tried Azure CLI, Github actions, Terraform and portal. All the same error message. Works fine with admin credentials but not managed identity.
