### ISSUE TITLE
Group Permissions Do Not Flow to Aspire Dashboard (Container App Environment)

### ISSUE THREAD

**Issue by Mike-E-angelo** [microsoft/azure-container-apps#1281]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description

When applying role assignments to the Container App Environment hosting the Aspire Dashboard, role assignments applied to users work whereas role assignments applied to Groups do not.

### Steps to reproduce
1. Create Entry ID Group
2. Add user to group
3. Assign Contributor Role Assignment to group
4. Access Aspire Dashboard
5. Observe `Could not authenticate user with requested resource.`
6. Assign Contributor Role Assignment to user
7. Access Aspire Dashboard
8. Observe expected loading of dashboard without error

**Expected behavior** [What you expected to happen.]

Aspire Dashboard loads when member is part of a Group that has Contributor Role Assignment

**Actual behavior** [What actually happened.]

Member that is part of a group with Contributor Role Assignment cannot access Aspire Dashboard and is presented with `Could not authenticate user with requested resource.` error.

**Screenshots**         
NA

### Additional context
Thank you for all your efforts out there. 🙏

**Comment by simonjj** [comment]
Closing as a duplicate of #1280

**Comment by simonjj** [comment]
Reopening, these are related but not duplicates.

**Comment by simonjj** [comment]
We've identified this issue and are working on a fix.

**Comment by maldworth** [comment]
Any ETA on this fix?

**Comment by xt1** [comment]
We see this on non-Windows users - they must have per-user Contributor role assignments on the Container App Environment to see the dashboard.

They also need role-assignments to see the Containers - which is a pain to automate because the containers are not described in bicep files, but rather ARM template YAML files - with no obvious place to add the role assignments.

The schema/format for these generated container template YAML files isn't documented anywhere.

**Comment by william-msft** [comment]
@Mike-E-angelo @maldworth @xt1 we have implemented a fix in the `westcentralus` region. I am reaching out to inquire if anyone experiences the same group permissions errors in that region. Please let me know if you would like to discuss this further.

**Comment by maldworth** [comment]
@william-msft  Can you let me know when it's in canada central region? I'll try it out then.

**Comment by lesterbotello** [comment]
> [@william-msft](https://github.com/william-msft) Can you let me know when it's in canada central region? I'll try it out then.

Looking for this as well, I'm in Canada East region and I seem to have the issue still.

**Comment by rrussell0** [comment]
This is still an issue for our users - West US region.

**Comment by d-barker** [comment]
Seeing this issue in Australia East as well

**Comment by kkarballof** [comment]
Any updates on this?

**Comment by kkarballof** [comment]
Can anyone confirm the fix works on "westcentralus"? And if yes when will be made available to all other regions?

**Comment by rrussell0** [comment]
This bug is really a huge pain when you have a large number of developers that would like to access an Aspire dashboard... would love to know if there's any plans to fix this bug.

**Comment by AdrianoAE** [comment]
Any update?
