### ISSUE TITLE
Error while deploying using bicep 

### ISSUE THREAD

**Issue by tomaxsas** [microsoft/azure-container-apps#1282]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [x ] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Started to get error: InvalidEnvironmentId\n\t\tMessage: EnvironmentId '[reference(resourceId('Microsoft.Resources/deployments', 'container-app-environment'), '2022-09-01').outputs.id.value]
No code changes were done, on CI started to appear 1.5 Days ago

### Steps to reproduce
1. Run az bicep build
2. Run Deployment via Azure rm

**Expected behavior** [What you expected to happen.]

Deployment succeeded

**Actual behavior** [What actually happened.]

Deployment fails with error
InvalidEnvironmentId\n\t\tMessage: EnvironmentId '[reference(resourceId('Microsoft.Resources/deployments', 'container-app-environment'), '2022-09-01').outputs.id.value]

### Additional context
CLI

**Comment by tomaxsas** [comment]
Narrowed down only to container apps jobs. Using API 'Microsoft.App/jobs@2024-03-01'

**Comment by Erick151** [comment]
Same issue here... I use a similar logic to set this value from the output of a different deployment, I have not done any changes and I receive the same error, what changed?

**Comment by anthonychu** [comment]
@tomaxsas @Erick151 Can you please email the resource IDs of your jobs to acasupport@ microsoft.com? Thanks!

**Comment by anthonychu** [comment]
If you’re able to, please send an email anyway and someone on the Container Apps jobs team can investigate also. Please include the resource ID and timeframe in which the error occurred. Thanks.

**Comment by vinisoto** [comment]
Thank you for reporting - we have found a potential regression. We are investigating and will update this thread with an ETA for the fix.

**Comment by vinisoto** [comment]
UPDATE:

The regression impacts some Container App Jobs deployments through bicep/ARM templates that use language expressions for referencing resources. This regression impacts deployments on East Aia, West Central US and West US 2.

We are rolling out a fix. We estimate the fix to be fully rolled out in 24 hours.

**Comment by vinisoto** [comment]
FIXED

The fix has been deployed to the impacted regions.

**Comment by Erick151** [comment]
Hi @vinisoto  , thanks for all the information you have shared over the last few days... I have now attempted this and all deployments are now fixed.

I have however found that the issue is still happening on the east us 2 region... I see that this region was not mentioned on your initial assessment of the regression, is this just an issue with the roll out not having reached this region?... Or was the same not taken into account for the fix?

**Comment by davidbambridgeeptura** [comment]
For anyone else who comes across this thread, this same issue is affecting the West Europe region.

**Comment by Erick151** [comment]
Yes, @vinisoto can you please review the issue again, I have indeed confirmed the issue has been fixed on the regions you specified... However I am also using the EastUS2 region and facing the problem still.

I see another comment mentioning the failure on west Europe, I have not tested other regions but can fully confirm same original issue on EastUS2
