### ISSUE TITLE
otel-collector connection refused

### ISSUE THREAD

**Issue by scottydog75** [microsoft/azure-container-apps#330]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
Receiving a large number of errors logged with the following detail:

ContainerName_s: daprd
Stream_s: stderr
Log_s: 2022/07/29 01:05:01 failed to send the request: Post "http://otel-collector.k8se-apps.svc.cluster.local:9411/api/v2/spans": dial tcp 10.0.127.104:9411: connect: connection refused

### Steps to reproduce
1. starts logging after deployment of the container

**Expected behavior** [What you expected to happen.]
Connection allowed and no logging of the error

**Actual behavior** [What actually happened.]
Connection refused and error logged

**Screenshots**         

### Additional context
Possibly a configuration missed, but I couldn't see any particular settings that refered to the otel-collector.

**Comment by k33lan** [comment]
Getting the same issue as well. This has just started recently.

**Comment by aschwab** [comment]
Im also experiencing this issue without any knowledge of changing something according to telemetry.

**Comment by chinadragon0515** [comment]
We are deploying the fix for the issue now, we expect the fix will be rolled out to all regions by tomorrow.

**Comment by chinadragon0515** [comment]
We have deployed the fix to all regions, let us know if you still meet issues. thanks

**Comment by scottydog75** [comment]
Still seeing the message in the logs - Australia East:

2022/08/08 03:52:07 failed to send the request: Post "http://otel-collector.k8se-apps.svc.cluster.local:9411/api/v2/spans": dial tcp 10.0.237.254:9411: connect: connection refused

**Comment by cbellee** [comment]
I'm also seeing the same issue for an ACA environment in Australia East.

2022/08/10 22:34:46 failed to send the request: Post "http://otel-collector.k8se-apps.svc.cluster.local:9411/api/v2/spans": dial tcp 10.1.71.151:9411: connect: connection refused

**Comment by kendallroden** [comment]
I believe this issue has been resolved and rolled out to all regions- can you confirm @chinadragon0515
