### ISSUE TITLE
Switching the traffic between two revisions via CLI/REST API not working

### ISSUE THREAD

**Issue by eliasmueller** [microsoft/azure-container-apps#790]
### This issue is a:
- [x] bug report
- [ ] documentation issue or request
- [x] regression (I could not really find an exact release when it started)

### Issue description
The switching of ingress traffic between two revisions of a container app is not returning a strange error, thus resulting in failing for both az cli and REST API.

### Steps to reproduce
1. Deploy a new container app revision in multi-revision-mode via ARM or Bicep template. Configure the template the way, that the old revision still has 100% of the ingress traffic. 
2. After successful deployment of the latest revision, both are in state "provisioned".
3. Now, try to switch the traffic by either using the az cli with
`az containerapp ingress traffic set -n $CONTAINER_APP_NAME -g $RESOURCE_GROUP --revision-weight $REVISION=100`
or with using the REST API with
```
PATCH https://management.azure.com/subscriptions/subscriptionId/resourceGroups/ressourceGroup/providers/Microsoft.App/containerApps/ppa-connect-bff-dev?api-version=2022-10-01

{
  "location": "West Europe",
  "properties": {
    "environmentId": "environmentId",
    "configuration": {
      "ingress": {
        "traffic": [
          {
            "latestRevision": true,
            "weight": 100
          }
        ]
      }
    }
  }
}
```

**Expected behavior** Now I would expect Azure Container Apps to switch the traffic of the revisions.

**Actual behavior** Actually, an error occurs, that states:
```
{
    "error": {
        "code": "InvalidParameterValueInContainerTemplate",
        "message": "The following field(s) are either invalid or missing. Field 'template.revisionsuffix' is invalid with details: 'Invalid value: \"20230615t100346z\": revision with suffix 20230615t100346z already exists.';."
    }
}
```

### Additional context
As this happens in the CLI as well as with the API, I assume it is an issue in container apps itself.

**Comment by vturecek** [comment]
@eliasmueller thanks for reporting this and providing detailed repro steps. I found a very subtle bug on our end that can produce this error in certain cases. I will follow up with a fix.

**Comment by denniszielke** [comment]
@vturecek can you update the status? Has the bug been released?

**Comment by smzeng** [comment]
@denniszielke hi, the bug fix has been completed but not yet been released. Following our normal release cadence the bug fix should be released in all regions in roughly 3 weeks.

**Comment by eliasmueller** [comment]
Hi @smzeng just checking in what the current status is, as three weeks have passed by now :)

**Comment by smzeng** [comment]
Hi @eliasmueller the fix has been deployed globally. Please let me know if you still run into issues.

**Comment by rmajid2** [comment]
Hi @smzeng still having the error (West europe region).

Command :
`az containerapp ingress traffic set -g <rg-name> -n <name>  --revision-weight "<revision>=100"`

Error :

> (InvalidParameterValueInContainerTemplate) The following field(s) are either invalid or missing. Field 'template.revisionsuffix' is invalid with details: 'Invalid value: "<revision>": revision with suffix <revision> already exists.';.

**Comment by smzeng** [comment]
@rmajid2 thanks for letting me know. I am investigating why this is still occurring and will provide updates as soon as possible.

**Comment by smzeng** [comment]
@rmajid2 could you send your app name and subid for the app your facing this problem to acasupport@microsoft.com for quicker investigation. Thank you!

**Comment by smzeng** [comment]
Hi @rmajid2 just want to follow up to see if you have emailed yet?
If you have can reply to that email with this issue link because we are having a hard time locating your email, thank you.
