### ISSUE TITLE
ContainerApp up command fails to pull image from private registry with admin credentials disabled

### ISSUE THREAD

**Issue by barumugham** [microsoft/azure-container-apps#821]
### This issue is a: (mark with an x)
- [ ] bug report -> please search issues before submitting

### Issue description
I am trying to update a ContainerApp with a image from a private repository. The containerApp has been created with the bicep file
The containerApp is created with the help of bicep file and it uses a default public image.

resource containerApp 'Microsoft.App/containerApps@2023-04-01-preview'  = {
  name: containerAppName
  location: location
  properties: {
    managedEnvironmentId: containerAppManagedEnvironment.id
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 80

      }
    }
    template: {
      containers: [
        {
          name: 'my-app'
          command: []
          image: 'mcr.microsoft.com/azuredocs/aci-helloworld'
          resources: {
            cpu: json('0.25')
            memory: '.5Gi'
          }
        }
      ]
    }
  }
}
The containerApp is successfully created and. i am able to browse to that.
A ACR registry(premium edition) is also created with public network access and **admin login credentials** disabled.

### Steps to reproduce
1. I create a azure pipeline task from devops which runs with an agent pool enabled with VMSS(Virtual Machine Scale Set) which should do
-push a nodejs application image to the ACR created above
-update the containerApp with the existing image from ACR

I already give the permissions to the containerApp;
- az containerapp identity assign(to create a system assigned managed identity)
- az role assignment create (to assign the acr pull role on the registry)
- az containerapp registry set (to delegate the managed identity to pull image from ACR)

The following lines of code are present in yaml file

stage: DeployContainerApp
  displayName: Deploy the Image as a Container app
  condition: and(succeeded(),or(eq(variables['Build.SourceBranchName'], 'dev'),eq(variables['Build.SourceBranchName'], 'branch2'),eq(variables['Build.SourceBranchName'], 'mybranch'))) 
  jobs:
  - job: DeployContainerApp
    displayName: Deploy Container App Job
    steps:
    - task: AzureContainerApps@1
      inputs:
        azureSubscription: $(armDeploymentServiceConnection)
        containerAppName: $(CONTAINER_APP_NAME)
        resourceGroup: $(RG_NAME)
        imageToDeploy: $(acrContainerRegistry).azurecr.io/$(imageRep)-$(Build.SourceBranchName):latest
        containerAppEnvironment: $(CONTAINER_APP_ENV_NAME)
        location: $(CONTAINER_APP_ENV_LOCATION_NAME)
        ingress: "external"
        targetPort: 80

The previous task already builds a Docker image and pushes it successfully to the private ACR. The above task should make the containerApp pull the ACR image and modify it.
**Expected behavior** 
This should update the containerApp with the image from ACR 
**Actual behavior** 
**`Failed to retrieve credentials for container registry. Please provide the registry username and password`**
Logs below:
**Screenshots**         
<img width="813" alt="screenshot2" src="https://github.com/microsoft/azure-container-apps/assets/7260206/a4d2d52d-13c5-49a5-8e0c-36d33e51adc6">
<img width="806" alt="screenshot1" src="https://github.com/microsoft/azure-container-apps/assets/7260206/58b92a58-8a01-41b9-82b0-2588906abb17">
<img width="1368" alt="role_assgined_azrpull" src="https://github.com/microsoft/azure-container-apps/assets/7260206/95591a4a-83e4-4d2d-89fc-67f0b0ae9d29">

### Additional context
The same issue also happens in the AZ cli when i run the following command after assigning necessary permissions to the containerApp
az containerapp up -n mycontainerapp -g my-rg -i myregistry.azurecr.io/myrepos-dev:latest --ingress external --target-port 80 --env-vars REDIRECT_URL=https://my-new-containerapp.salmonbush-deseaedc4c.eastus.azurecontainerapps.io

<img width="1132" alt="local_error" src="https://github.com/microsoft/azure-container-apps/assets/7260206/3bb49e49-684f-4c64-890e-293440ba75f7">

Any suggestions here?

**Comment by daniv-msft** [comment]
Thanks @barumugham for reporting this issue! We're looking into this to determine how we can fix this. Adding @harryli0108 for FYI.

**Comment by letmaik** [comment]
Same issue here, had to enable admin credentials which is quite unfortunate.

**Comment by Blind-Watchmaker** [comment]
I have a similar issue. I would like to continue to use my service principal to access images in my private ACR, but of course this prevents me from using a command like:

```
          az containerapp update \
          -n  ${{ secrets.CONTAINER_APPLICATION_NAME }} \
          -g ${{ secrets.RESOURCE_GROUP_NAME }} \
          --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} \
          --image <IMAGE_NAME>
```

As far as I'm aware, `az containerapp` expects admin credentials to get the image from the ACR. If you go into the Portal, you need to manually specify the image and the tag there and then it will know how to get the image.

**Comment by sebappale** [comment]
I have this exact problem. Is there no solution yet? The only way to get this to work is to use username&password in the Devops task?

**Comment by harryli0108** [comment]
Hi all! I do apologize for the very delayed reply here.

This issue was caused by an underlying issue with the `containerapp up` command where the command required to have admin credentials for the registry. The reason why we used `up` command in the first place is because the `containerapp ingress enable` command would reset the ingress info during an update (this issue is now fixed with a new command `containerapp ingress update`), and `containerapp update` doesn't have ingress update options.

I'll update the github action script accordingly. I'll make sure to update the progress of the fix in this thread. Again, I'm sorry for the late reply here.

**Comment by forki** [comment]
We actually gave the container app job the admin access, but it still fails with:

`Failed to pull image "msuregistry.azurecr.io/mail2:7.296.10": [rpc error: code = NotFound desc = failed to pull and unpack image "msuregistry.azurecr.io/mail2:7.296.10": failed to resolve reference "msuregistry.azurecr.io/mail2:7.296.10": msuregistry.azurecr.io/mail2:7.296.10: not found, rpc error: code = Unknown desc = failed to pull and unpack image "msuregistry.azurecr.io/mail2:7.296.10": failed to resolve reference "msuregistry.azurecr.io/mail2:7.296.10": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://msuregistry.azurecr.io/oauth2/token?scope=repository%3Amail2%3Apull&service=msuregistry.azurecr.io: 401 Unauthorized]`

Environment: ecarenv 
Resource Group: ecar
Region: West Europe

**Comment by dtriana** [comment]
I'm following the same tutorial posted above by @sebappale , https://learn.microsoft.com/en-us/azure/container-apps/azure-pipelines , but with a specific requirement, my ACR lives on its own subscription, not the same as the containers environment,

I have admin creds enabled on ACR and I have used `az containerapp registry set` for user managed, system managed, username and password, no luck,

via az containerapp up I get the same error message shared at the start of this thread, and via the AzDevOps AzureContainerApps@1 task, its able to build the image, but when deploying it fails with

`The resource with name '---nameofmyacr---' and type 'Microsoft.ContainerRegistry/registries' could not be found in subscription '---name and guid of the susbscription of my app---'.` which is truth, but why it's looking into azure instead of using the provided username/password either from the containerapp registry or directly in the parameters of the task, something that I tried as well,

is this scenario supposed to work? CI/CD with ACR in one Sub and the Container App in another, ideally with managed identities?

**Comment by harryli0108** [comment]
Hi @dtriana! I believe this is something we're currently fixing as well. This is also caused by an underlying issue in the CLI that the GitHub Action uses. Normally, by specifying the full registry server URL and registry username and password should allow the command to authenticate with any registry. 

Tagging @cormacpayne who's looking into this issue currently. Please feel free to correct me if I'm wrong and pitch in anytime!

**Comment by harryli0108** [comment]
Hi all! The changes are now merged and live in the v2 prerelease. Please feel free to test it out and let me know if there's any issue with it!

Meanwhile, the fix of the issue with ACR auth from different subscription is still in progress.

I'll keep this issue opened for a few days and close it if no additional problems are found.

**Comment by dtriana** [comment]
Just to add a detail on my scenario, ACR on its own subscription, with password, using `az containerapp create`  works fine, its `az containerapp up` the one that fails with that error about the ACR not in the same sub, and unfortunately this is the one used by the AzDevOps AzureContainerApps@1 task when the app already exist,

`az containerapp update` also works, the issue at least for me seems to be only with `up`,

looks like getting rid of the AzureContainerApps@1 task and adding my own cli with the proper create or update logic is the way to go for me

**Comment by harryli0108** [comment]
@dtriana Thank you for the additional info! Sorry for the inconvenience this creates. This issue is definitely on our radar. However, the fix may take longer to implement since this require us to make changes in the CLI extension where `up` command is located.

Meanwhile, I'll close this issue for now since the problem seems to be fixed. Thank you all!

**Comment by anthonychu** [comment]
Closing as fixed

**Comment by harryli0108** [comment]
Hi @EdiFirst!
If you're using the Github Action, please make sure you're using the latest v2 version of the action.
We're currently fixing the same issue in our ADO task as well. We'll first release our fix on our ADO RC task by the end of this week. I'll make sure to keep you posted in this thread when the issue in ADO task is released as well

**Comment by EdiFirst** [comment]
Thank you @harryli0108 

Yes I'm using Az cli commando on ADO using bicep to deploy. I tried to use the spn token to authenticate on ACR using properties directly on ACA resource bicep , but get errors too.

**Comment by GG-ACSResearch** [comment]
Any news on the ADO task?

**Comment by daniv-msft** [comment]
I believe that the ADO RC task is fixed already, and that the ADO official task fix will be part of the next deployment. @harryli0108 Could you please confirm?

**Comment by mihohoi0322** [comment]
@daniv-msft , @harryli0108 
Hi, 
I haven't seen any updates recently; could you please provide the current status of the new task version? Also, is enabling admin credentials still the recommended temporary workaround?

**Comment by ubk1004** [comment]
I can confirm as of 2025-03-14 the issue is still there.

I am using the following task in my DevOps pipeline, it's able to build the image and push the given ACR successfully. But fails to deploy to the container App.

```
- task: AzureContainerApps@1
  inputs:
    connectedServiceNameARM: 'Digital-Worker-Service-Connection'
    appSourcePath: '$(System.DefaultWorkingDirectory)/MyApi'
    dockerfilePath: 'Dockerfile'
    acrName: '$(containerRegistryName)'
    containerAppName: $(jobManagerContainerAppName)
    resourceGroup: $(resourceGroup)
    imageToBuild: '$(containerRegistry)/$(jobManagerImageRepository):latest'
    imageToDeploy: '$(containerRegistry)/$(jobManagerImageRepository):latest'
    containerAppEnvironment: $(containerAppEnvironment)
    runtimeStack: 'dotnetcore:8.0'
    ingress: "external"
    targetPort: 8080
```

![Image](https://github.com/user-attachments/assets/c47cc2c4-1847-4ba9-9c1b-1eb12ef67b2a)

What was the solution to the issue reported almost 1.5 years back?

**Comment by tuzz** [comment]
Still occurring. The admin_user has to be enabled for AcrPull to work.

**Comment by peyton-smith-kh** [comment]
Can confirm this is still an issue as of 1/4/2026. If I add any additional settings to the ACR task such as --targetport 5000 the CLI command during the pipeline run will switch from "az containerapp update" to "azcontainer app up" which then forces admin credentials to be provided.

Is there any update on when/if this issue will be resolved? Looks like this has been open for years.
