### ISSUE TITLE
Connection timeout when running Container App connected to a Secure Virtual Wan/AzureFirewall

### ISSUE THREAD

**Issue by JonasCordsen** [microsoft/azure-container-apps#966]
### This issue is a: (mark with an x)
- [x] bug report -> please search issues before submitting
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Issue description
We are trying to use Container Apps Jobs to run out Azure DevOps selfhosted agents.
The agents are located behind a Secure Virtual Wan, the pipeline that uses these agents, runs a bunch of REST API calls to azure.

Unfortunately we are facing connections timeout issues that seem to be related to Container apps and Secure Virtual Wan/Azure Firewall.

### Steps to reproduce
I have tested the pipeline with 10 Runs on both AKS and Contianer apps

First test Container App Jobs via Secure Virtual Wan
Timeout on connections on 7/10 runs

First test AKS via Secure Virtual Wan
Timeout on connections on 0/10 runs

First test Container App Jobs without Secure Virtual Wan
Timeout on connections on 0/10 runs

**Expected behavior** [What you expected to happen.]
I would expect connections to be consistent, and not have lille to none connection timeouts

**Comment by cachai2** [comment]
Hi @JonasCordsen, we did find that there was a bug which was causing connection issues in ACA and was fixed end of November, can you let me know if you're still running into this issue? If so, can you open up a support case to share more details, so we can investigate?

**Comment by JonasCordsen** [comment]
Hey @cachai2 sadly the issue is still precent for us.
We do have an open case, but there is not much progress

**Comment by dsczltch** [comment]
We have a "similar" issue where when routing traffic to firewall through UDR, we have latency issue with Container App.
We do not have latency with App service in a similiar configuration.
